# Generated by Django 4.0.2 on 2022-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('bio', models.TextField(null=True)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
