# Generated by Django 4.0.2 on 2022-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('star', '0001_initial'),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('published', models.CharField(max_length=10)),
                ('duration', models.PositiveSmallIntegerField()),
                ('votes', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('directors', models.ManyToManyField(related_name='movies', to='director.Director')),
                ('genres', models.ManyToManyField(related_name='movies', to='genre.Genre')),
                ('stars', models.ManyToManyField(related_name='movies', to='star.Star')),
            ],
        ),
    ]
